import { Prayer } from '../types';

export const prayers: Prayer[] = [
  {
    id: 'sinal_da_cruz',
    title: 'Sinal da Cruz',
    category: 'Orações Tradicionais',
    body: 'Pelo sinal da Santa Cruz, livrai-nos, Deus, Nosso Senhor, dos nossos inimigos. Em nome do Pai, do Filho e do Espírito Santo. Amém.',
  },
  {
    id: 'pai_nosso',
    title: 'Pai-Nosso',
    category: 'Orações Tradicionais',
    body: 'Pai nosso que estais nos céus, santificado seja o vosso nome. Venha a nós o vosso Reino. Seja feita a vossa vontade, assim na terra como no céu. O pão nosso de cada dia nos dai hoje. Perdoai-nos as nossas ofensas, assim como nós perdoamos a quem nos tem ofendido. E não nos deixeis cair em tentação, mas livrai-nos do mal. Amém.',
  },
  {
    id: 'ave_maria',
    title: 'Ave-Maria',
    category: 'Orações Tradicionais',
    body: 'Ave Maria, cheia de graça, o Senhor é convosco. Bendita sois vós entre as mulheres e bendito é o fruto do vosso ventre, Jesus. Santa Maria, Mãe de Deus, rogai por nós, pecadores, agora e na hora de nossa morte. Amém.',
  },
  {
    id: 'gloria_ao_pai',
    title: 'Glória ao Pai',
    category: 'Orações Tradicionais',
    body: 'Glória ao Pai, ao Filho e ao Espírito Santo. Como era no princípio, agora e sempre. Amém.',
  },
  {
    id: 'credo_apostolico',
    title: 'Creio',
    category: 'Orações Tradicionais',
    body: 'Creio em Deus Pai todo-poderoso, criador do céu e da terra; e em Jesus Cristo, seu único Filho, nosso Senhor, que foi concebido pelo poder do Espírito Santo, nasceu da Virgem Maria, padeceu sob Pôncio Pilatos, foi crucificado, morto e sepultado; desceu à mansão dos mortos; ressuscitou ao terceiro dia; subiu aos céus; está sentado à direita de Deus Pai todo-poderoso, de onde há de vir a julgar os vivos e os mortos. Creio no Espírito Santo, na santa Igreja Católica, na comunhão dos santos, na remissão dos pecados, na ressurreição da carne e na vida eterna. Amém.',
  },
  {
    id: 'confesso',
    title: 'Confesso a Deus',
    category: 'Ato de Contrição',
    body: 'Confesso a Deus todo-poderoso e a vós, irmãos e irmãs, que pequei muitas vezes por pensamentos e palavras, atos e omissões, por minha culpa, minha culpa, minha tão grande culpa. E peço à Virgem Maria, aos anjos e santos, e a vós, irmãos e irmãs, que rogueis por mim a Deus, nosso Senhor.',
  },
  {
    id: 'ato_contricao_tradicional',
    title: 'Ato de Contrição',
    category: 'Ato de Contrição',
    body: 'Meu Deus, eu me arrependo de todo o coração de Vos ter ofendido, porque sois tão bom e amável. Prometo, com o auxílio da vossa graça, confessar-me, fazer penitência e nunca mais Vos tornar a ofender. Amém.',
  },
  {
    id: 'ato_contricao_breve',
    title: 'Ato de Contrição Breve',
    category: 'Ato de Contrição',
    body: 'Meu Deus, tende piedade de mim, pecador. Dai-me dor sincera dos meus pecados e firme propósito de emenda. Amém.',
  },
  {
    id: 'vinde_espirito_santo',
    title: 'Vinde, Espírito Santo',
    category: 'Espírito Santo',
    body: 'Vinde, Espírito Santo, enchei os corações dos vossos fiéis e acendei neles o fogo do vosso amor. Enviai o vosso Espírito e tudo será criado, e renovareis a face da terra. Oremos: Ó Deus, que instruístes os corações dos vossos fiéis com a luz do Espírito Santo, fazei que apreciemos retamente todas as coisas segundo o mesmo Espírito e gozemos sempre da sua consolação. Por Cristo, Senhor nosso. Amém.',
  },
  {
    id: 'espirito_santo_luz',
    title: 'Luz para a Consciência',
    category: 'Espírito Santo',
    body: 'Espírito Santo, luz das almas, iluminai minha consciência. Mostrai-me onde preciso mudar, dai-me humildade para reconhecer minhas faltas e coragem para voltar ao caminho de Deus. Amém.',
  },
  {
    id: 'oracao_preparatoria_exame',
    title: 'Antes do Exame de Consciência',
    category: 'Antes do Exame',
    body: 'Meu Senhor e meu Deus, dai-me luz para reconhecer meus pecados, humildade para não me justificar, dor sincera por Vos ter ofendido e força para mudar de vida. Amém.',
  },
  {
    id: 'conhecer_pecados',
    title: 'Para Conhecer os Próprios Pecados',
    category: 'Antes do Exame',
    body: 'Senhor, não permitais que eu me engane a mim mesmo. Mostrai-me minhas faltas com verdade e sustentai-me com a vossa misericórdia. Amém.',
  },
  {
    id: 'agradecimento_exame',
    title: 'Agradecimento no Exame',
    category: 'Antes do Exame',
    body: 'Senhor, antes de olhar minhas faltas, quero reconhecer vossas graças. Obrigado pela vida, pelas pessoas confiadas a mim e pelas oportunidades de amar. Amém.',
  },
  {
    id: 'antes_confissao',
    title: 'Antes da Confissão',
    category: 'Antes da Confissão',
    body: 'Senhor Jesus Cristo, iluminai minha memória para que eu me recorde dos meus pecados. Dai clareza ao meu entendimento, arrependimento ao meu coração e confiança na vossa misericórdia. Amém.',
  },
  {
    id: 'vencer_vergonha',
    title: 'Para Vencer a Vergonha',
    category: 'Antes da Confissão',
    body: 'Senhor, dai-me simplicidade para dizer a verdade, sem esconder o que me envergonha e sem aumentar ou diminuir meus pecados. Que eu confesse com humildade e confiança. Amém.',
  },
  {
    id: 'bom_proposito',
    title: 'Por Firme Propósito',
    category: 'Antes da Confissão',
    body: 'Jesus misericordioso, dai-me um propósito concreto, humilde e possível. Que eu não confie em minhas forças, mas na vossa graça. Amém.',
  },
  {
    id: 'depois_confissao',
    title: 'Depois da Confissão',
    category: 'Depois da Confissão',
    body: 'Senhor Jesus Cristo, eu Vos agradeço pela absolvição sacramental e pela vossa misericórdia. Guardai-me na paz, ajudai-me a cumprir a penitência e sustentai meu propósito. Amém.',
  },
  {
    id: 'acao_gracas_confissao',
    title: 'Ação de Graças',
    category: 'Depois da Confissão',
    body: 'Pai de misericórdia, obrigado por me receber de volta. Que a paz deste sacramento dê frutos de caridade, reparação e vigilância. Amém.',
  },
  {
    id: 'salve_rainha',
    title: 'Salve Rainha',
    category: 'Nossa Senhora',
    body: 'Salve, Rainha, Mãe de misericórdia, vida, doçura e esperança nossa, salve! A vós bradamos, os degredados filhos de Eva. A vós suspiramos, gemendo e chorando neste vale de lágrimas. Eia, pois, advogada nossa, esses vossos olhos misericordiosos a nós volvei; e depois deste desterro mostrai-nos Jesus, bendito fruto do vosso ventre. Ó clemente, ó piedosa, ó doce sempre Virgem Maria. Rogai por nós, Santa Mãe de Deus, para que sejamos dignos das promessas de Cristo. Amém.',
  },
  {
    id: 'a_vossa_protecao',
    title: 'À Vossa Proteção',
    category: 'Nossa Senhora',
    body: 'À vossa proteção recorremos, Santa Mãe de Deus. Não desprezeis as nossas súplicas em nossas necessidades, mas livrai-nos sempre de todos os perigos, ó Virgem gloriosa e bendita. Amém.',
  },
  {
    id: 'nossa_senhora_confissao',
    title: 'A Nossa Senhora antes da Confissão',
    category: 'Nossa Senhora',
    body: 'Nossa Senhora, Mãe de misericórdia, acompanhai-me até o confessionário. Dai-me confiança, sinceridade e um coração arrependido. Amém.',
  },
  {
    id: 'anjo_guarda',
    title: 'Santo Anjo do Senhor',
    category: 'Proteção',
    body: 'Santo Anjo do Senhor, meu zeloso guardador, se a ti me confiou a piedade divina, sempre me rege, guarda, governa e ilumina. Amém.',
  },
  {
    id: 'sao_miguel',
    title: 'São Miguel Arcanjo',
    category: 'Proteção',
    body: 'São Miguel Arcanjo, defendei-nos no combate. Sede o nosso refúgio contra as maldades e ciladas do demônio. Ordene-lhe Deus, instantemente o pedimos; e vós, príncipe da milícia celeste, pelo divino poder, precipitai no inferno a Satanás e a todos os espíritos malignos que andam pelo mundo para perder as almas. Amém.',
  },
  {
    id: 'alma_de_cristo',
    title: 'Alma de Cristo',
    category: 'Perseverança e Pureza',
    body: 'Alma de Cristo, santificai-me. Corpo de Cristo, salvai-me. Sangue de Cristo, inebriai-me. Água do lado de Cristo, lavai-me. Paixão de Cristo, confortai-me. Ó bom Jesus, ouvi-me. Dentro de vossas chagas, escondei-me. Não permitais que eu me separe de Vós. Do inimigo maligno, defendei-me. Na hora da minha morte, chamai-me e mandai-me ir para Vós, para que com os vossos santos Vos louve por todos os séculos. Amém.',
  },
  {
    id: 'pedindo_pureza',
    title: 'Pedindo Pureza',
    category: 'Perseverança e Pureza',
    body: 'Jesus castíssimo, guardai meu olhar, minha imaginação, meus afetos e meu corpo. Dai-me um coração puro e decidido a fugir da ocasião de pecado. Amém.',
  },
  {
    id: 'perseveranca',
    title: 'Pedindo Perseverança',
    category: 'Perseverança e Pureza',
    body: 'Senhor, sei que sou fraco e que sem Vós nada posso fazer de bom. Concedei-me perseverança, prontidão para levantar após a queda e força para evitar as ocasiões de pecado. Amém.',
  },
  {
    id: 'latin_pater_noster',
    title: 'Pater Noster',
    category: 'Latim',
    body: 'Pater noster, qui es in caelis: sanctificetur Nomen Tuum; adveniat Regnum Tuum; fiat voluntas Tua, sicut in caelo et in terra. Panem nostrum quotidianum da nobis hodie; et dimitte nobis debita nostra, sicut et nos dimittimus debitoribus nostris; et ne nos inducas in tentationem; sed libera nos a Malo. Amen.',
  },
  {
    id: 'latin_ave_maria',
    title: 'Ave Maria',
    category: 'Latim',
    body: 'Ave, Maria, gratia plena, Dominus tecum. Benedicta tu in mulieribus, et benedictus fructus ventris tui, Iesus. Sancta Maria, Mater Dei, ora pro nobis peccatoribus, nunc et in hora mortis nostrae. Amen.',
  },
  {
    id: 'latin_gloria_patri',
    title: 'Gloria Patri',
    category: 'Latim',
    body: 'Gloria Patri, et Filio, et Spiritui Sancto. Sicut erat in principio, et nunc, et semper, et in saecula saeculorum. Amen.',
  },
  {
    id: 'latin_symbolum_apostolorum',
    title: 'Symbolum Apostolorum',
    category: 'Latim',
    body: 'Credo in Deum, Patrem omnipotentem, Creatorem caeli et terrae; et in Iesum Christum, Filium eius unicum, Dominum nostrum, qui conceptus est de Spiritu Sancto, natus ex Maria Virgine, passus sub Pontio Pilato, crucifixus, mortuus, et sepultus; descendit ad inferos; tertia die resurrexit a mortuis; ascendit ad caelos; sedet ad dexteram Dei Patris omnipotentis; inde venturus est iudicare vivos et mortuos. Credo in Spiritum Sanctum, sanctam Ecclesiam catholicam, sanctorum communionem, remissionem peccatorum, carnis resurrectionem, vitam aeternam. Amen.',
  },
  {
    id: 'latin_symbolum_nicaenum',
    title: 'Symbolum Nicaenum-Constantinopolitanum',
    category: 'Latim',
    body: 'Credo in unum Deum, Patrem omnipotentem, factorem caeli et terrae, visibilium omnium et invisibilium. Et in unum Dominum Iesum Christum, Filium Dei unigenitum, et ex Patre natum ante omnia saecula. Deum de Deo, Lumen de Lumine, Deum verum de Deo vero, genitum, non factum, consubstantialem Patri; per quem omnia facta sunt. Qui propter nos homines et propter nostram salutem descendit de caelis. Et incarnatus est de Spiritu Sancto ex Maria Virgine, et homo factus est. Crucifixus etiam pro nobis sub Pontio Pilato; passus et sepultus est, et resurrexit tertia die secundum Scripturas, et ascendit in caelum, sedet ad dexteram Patris. Et iterum venturus est cum gloria, iudicare vivos et mortuos, cuius regni non erit finis. Et in Spiritum Sanctum, Dominum et vivificantem, qui ex Patre Filioque procedit. Qui cum Patre et Filio simul adoratur et conglorificatur; qui locutus est per prophetas. Et unam, sanctam, catholicam et apostolicam Ecclesiam. Confiteor unum baptisma in remissionem peccatorum. Et expecto resurrectionem mortuorum, et vitam venturi saeculi. Amen.',
  },
  {
    id: 'latin_salve_regina',
    title: 'Salve Regina',
    category: 'Latim',
    body: 'Salve, Regina, Mater misericordiae, vita, dulcedo et spes nostra, salve. Ad te clamamus, exsules filii Evae. Ad te suspiramus, gementes et flentes in hac lacrimarum valle. Eia ergo, advocata nostra, illos tuos misericordes oculos ad nos converte. Et Iesum, benedictum fructum ventris tui, nobis post hoc exsilium ostende. O clemens, o pia, o dulcis Virgo Maria.',
  },
  {
    id: 'latin_sub_tuum',
    title: 'Sub Tuum Praesidium',
    category: 'Latim',
    body: 'Sub tuum praesidium confugimus, Sancta Dei Genitrix; nostras deprecationes ne despicias in necessitatibus, sed a periculis cunctis libera nos semper, Virgo gloriosa et benedicta.',
  },
  {
    id: 'latin_anima_christi',
    title: 'Anima Christi',
    category: 'Latim',
    body: 'Anima Christi, sanctifica me. Corpus Christi, salva me. Sanguis Christi, inebria me. Aqua lateris Christi, lava me. Passio Christi, conforta me. O bone Iesu, exaudi me. Intra tua vulnera absconde me. Ne permittas me separari a te. Ab hoste maligno defende me. In hora mortis meae voca me, et iube me venire ad te, ut cum Sanctis tuis laudem te in saecula saeculorum. Amen.',
  },
  {
    id: 'latin_veni_creator',
    title: 'Veni Creator Spiritus',
    category: 'Latim',
    body: 'Veni, Creator Spiritus, mentes tuorum visita, imple superna gratia quae tu creasti pectora. Qui diceris Paraclitus, altissimi donum Dei, fons vivus, ignis, caritas, et spiritalis unctio.',
  },
  {
    id: 'latin_tantum_ergo',
    title: 'Tantum Ergo',
    category: 'Latim',
    body: 'Tantum ergo Sacramentum veneremur cernui; et antiquum documentum novo cedat ritui; praestet fides supplementum sensuum defectui. Genitori Genitoque laus et iubilatio, salus, honor, virtus quoque sit et benedictio; procedenti ab utroque compar sit laudatio. Amen.',
  },
  {
    id: 'latin_sancte_michael',
    title: 'Sancte Michael Archangele',
    category: 'Latim',
    body: 'Sancte Michael Archangele, defende nos in proelio; contra nequitiam et insidias diaboli esto praesidium. Imperet illi Deus, supplices deprecamur; tuque, Princeps militiae caelestis, Satanam aliosque spiritus malignos, qui ad perditionem animarum pervagantur in mundo, divina virtute in infernum detrude. Amen.',
  },
  {
    id: 'latin_crux_sancti_benedicti',
    title: 'Crux Sancti Patris Benedicti',
    category: 'Latim',
    body: 'Crux sacra sit mihi lux; non draco sit mihi dux. Vade retro, Satana; numquam suade mihi vana. Sunt mala quae libas; ipse venena bibas.',
  },
  {
    id: 'latin_oratio_sancti_benedicti',
    title: 'Oratio ad Sanctum Benedictum',
    category: 'Latim',
    body: 'O sancte Pater Benedicte, intercede pro nobis apud Deum, ut eius gratia muniti, tentationes vincamus, pacem diligamus et in via Christi perseveremus. Amen.',
  },
  {
    id: 'sao_francisco_instrumento_paz',
    title: 'Sao Francisco - Instrumento de Paz',
    category: 'Oracoes dos Santos',
    body: 'Senhor, fazei-me instrumento de vossa paz. Onde houver odio, que eu leve o amor; onde houver ofensa, o perdao; onde houver discordia, a uniao; onde houver duvida, a fe; onde houver erro, a verdade; onde houver desespero, a esperanca; onde houver tristeza, a alegria; onde houver trevas, a luz. Fazei que eu procure mais consolar que ser consolado, compreender que ser compreendido, amar que ser amado. Amen.',
  },
  {
    id: 'santo_inacio_tomai_senhor',
    title: 'Santo Inacio - Tomai, Senhor',
    category: 'Oracoes dos Santos',
    body: 'Tomai, Senhor, e recebei toda a minha liberdade, a minha memoria, o meu entendimento e toda a minha vontade. Tudo o que tenho e possuo Vos me destes; a Vos, Senhor, o restituo. Tudo e vosso; disponde de tudo segundo a vossa vontade. Dai-me somente o vosso amor e a vossa graca, que isto me basta. Amen.',
  },
  {
    id: 'santo_agostinho_conhecer',
    title: 'Santo Agostinho - Conhecer a Deus',
    category: 'Oracoes dos Santos',
    body: 'Senhor Jesus, que eu Vos conheca e me conheca. Que nada deseje senao a Vos. Que eu me esqueca de mim e Vos ame. Que eu faca tudo por Vos. Que eu me humilhe e Vos exalte. Que eu pense sempre em Vos. Amen.',
  },
  {
    id: 'sao_tomas_estudo',
    title: 'Sao Tomas de Aquino - Antes do Estudo',
    category: 'Oracoes dos Santos',
    body: 'Criador inefavel, fonte da luz e da sabedoria, derramai sobre as trevas da minha inteligencia um raio da vossa claridade. Dai-me agudeza para entender, capacidade para reter, metodo para aprender, sutileza para interpretar e graca abundante para falar. Amen.',
  },
  {
    id: 'santo_afonso_amor_jesus',
    title: 'Santo Afonso - Amor a Jesus',
    category: 'Oracoes dos Santos',
    body: 'Meu Jesus, eu Vos amo de todo o coracao. Arrependo-me de Vos ter ofendido. Nao permitais que eu torne a separar-me de Vos. Fazei que eu Vos ame sempre, e depois disponde de mim como quiserdes. Amen.',
  },
  {
    id: 'sao_bento_protecao',
    title: 'Sao Bento - Protecao',
    category: 'Protecao',
    body: 'A Cruz Sagrada seja a minha luz. Nao seja o dragao o meu guia. Retira-te, satanas; nunca me aconselhes coisas vas. E mau o que me ofereces; bebe tu mesmo os teus venenos. Amen.',
  },
  {
    id: 'memorare',
    title: 'Lembrai-vos',
    category: 'Nossa Senhora',
    body: 'Lembrai-vos, o piissima Virgem Maria, que nunca se ouviu dizer que algum daqueles que recorreram a vossa protecao, imploraram a vossa assistencia e reclamaram o vosso socorro fosse por Vos desamparado. Animado com igual confianca, a Vos recorro, o Virgem das virgens, minha Mae. Nao desprezeis as minhas suplicas, mas ouvi-me propicia e alcancai-me o que Vos peco. Amen.',
  },
  {
    id: 'angelus',
    title: 'Angelus',
    category: 'Nossa Senhora',
    body: 'O Anjo do Senhor anunciou a Maria, e ela concebeu do Espirito Santo. Ave-Maria. Eis aqui a serva do Senhor; faca-se em mim segundo a vossa palavra. Ave-Maria. E o Verbo se fez carne, e habitou entre nos. Ave-Maria. Rogai por nos, Santa Mae de Deus, para que sejamos dignos das promessas de Cristo. Oremos: infundi, Senhor, a vossa graca em nossas almas, para que, conhecendo pela anunciacao do anjo a encarnacao de Cristo, cheguemos por sua paixao e cruz a gloria da ressurreicao. Amen.',
  },
  {
    id: 'regina_caeli',
    title: 'Rainha do Ceu',
    category: 'Nossa Senhora',
    body: 'Rainha do Ceu, alegrai-vos, aleluia. Porque Aquele que merecestes trazer em vosso seio, aleluia, ressuscitou como disse, aleluia. Rogai por nos a Deus, aleluia. Exultai e alegrai-vos, o Virgem Maria, aleluia, porque o Senhor ressuscitou verdadeiramente, aleluia.',
  },
  {
    id: 'sao_jose',
    title: 'A Sao Jose',
    category: 'Protecao',
    body: 'A vos, Sao Jose, recorremos em nossa tribulacao. Depois de implorar o auxilio de vossa santissima Esposa, cheios de confianca solicitamos tambem o vosso patrocinio. Protegei a Igreja, guardai nossas familias e conduzi-nos no caminho de Jesus. Amen.',
  },
  {
    id: 'ato_fe',
    title: 'Ato de Fe',
    category: 'Virtudes Teologais',
    body: 'Meu Deus, creio firmemente em tudo o que revelastes e a santa Igreja nos propoe para crer, porque sois a propria verdade. Nesta fe quero viver e morrer. Amen.',
  },
  {
    id: 'ato_esperanca',
    title: 'Ato de Esperanca',
    category: 'Virtudes Teologais',
    body: 'Meu Deus, espero com firme confianca que, pelos merecimentos de Jesus Cristo, me dareis a salvacao eterna e as gracas necessarias para alcanca-la, porque sois infinitamente bom e fiel as vossas promessas. Amen.',
  },
  {
    id: 'ato_caridade',
    title: 'Ato de Caridade',
    category: 'Virtudes Teologais',
    body: 'Meu Deus, amo-Vos sobre todas as coisas, de todo o meu coracao, porque sois infinitamente bom e digno de todo amor. Por amor de Vos, amo tambem o meu proximo como a mim mesmo. Amen.',
  },
  {
    id: 'comunhao_espiritual_santo_afonso',
    title: 'Comunhao Espiritual',
    category: 'Eucaristia',
    body: 'Meu Jesus, eu creio que estais presente no Santissimo Sacramento. Amo-Vos sobre todas as coisas e desejo receber-Vos em minha alma. Ja que agora nao posso receber-Vos sacramentalmente, vinde ao menos espiritualmente ao meu coracao. Abraco-me convosco como se ja Vos tivesse recebido e uno-me todo a Vos. Nao permitais que eu me separe de Vos. Amen.',
  },
  {
    id: 'adoracao_santissimo',
    title: 'Adoracao ao Santissimo Sacramento',
    category: 'Eucaristia',
    body: 'Meu Senhor Jesus Cristo, presente no Santissimo Sacramento, eu Vos adoro com todo o meu coracao. Aumentai minha fe, inflamai meu amor e ensinai-me a permanecer convosco em silencio, reverencia e gratidao. Amen.',
  },
  {
    id: 'tantum_ergo_portugues',
    title: 'Tao Sublime Sacramento',
    category: 'Eucaristia',
    body: 'Tao sublime Sacramento adoremos neste altar, pois o Antigo Testamento deu ao Novo seu lugar. Venha a fe por suplemento os sentidos completar. Ao eterno Pai cantemos e a Jesus, o Salvador; ao Espirito exaltemos, na Trindade eterno amor. Ao Deus uno e trino demos a alegria do louvor. Amen.',
  },
];
